/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package upb.du.dti.isc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import upb.du.dti.isc.CompRuntimeModule;
import upb.du.dti.isc.CompStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CompIdeSetup extends CompStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CompRuntimeModule(), new CompIdeModule()));
	}
	
}
