/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package upb.du.dti.isc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CompUiModule extends AbstractCompUiModule {

	public CompUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
